FROM ros:noetic-ros-base 

RUN apt-get update && \
    apt-get install -y \
    ros-noetic-tf2-msgs \
    ros-noetic-tf2 \
    ros-noetic-tf2-ros \
    ros-noetic-rosbag \
    && rm -rf /var/lib/apt/lists/*
